//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPD_CollectorsDen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Tbl
    {
        public string Customer_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string cus_username { get; set; }
        public string cus_password { get; set; }
        public string email { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string cus_address { get; set; }
    }
}
