//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPD_CollectorsDen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_tbl
    {
        public string ProductID { get; set; }
        public string Product_Name { get; set; }
        public decimal Price { get; set; }
        public string StatusID { get; set; }
        public string CategoryID { get; set; }
        public string Product_Description { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Product_category Product_category { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
    }
}
